name: build

on:
  push:
    branches: ['master', 'STREAMS-*']
  pull_request:
    branches: ['master', 'STREAMS-*']
  schedule:
    # Run daily at 3pm UTC
    - cron: '0 15 * * *'

jobs:
  ubuntu-java-1-8:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    name: Ubuntu - Java 1.8
    steps:
      - name: Checkout apache/streams.git
        uses: actions/checkout@v2
      - name: Set up Java 1.8
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 1.8
      - name: Restore ~/.m2/repository
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository/
            !~/.m2/repository/org/apache/streams
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: mvn -B -V clean install -ff -ntp
        env:
          MAVEN_OPTS: -Xmx1g -XX:ReservedCodeCacheSize=1g -XX:+UseG1GC -Dorg.slf4j.simpleLogger.defaultLogLevel=INFO
        run: mvn -B -V clean install -ff -ntp
  macos-java-1-8:
    timeout-minutes: 60
    runs-on: macos-latest
    name: macOS - Java 1.8
    steps:
      - name: Get system hardware info 
        run: |
          system_profiler -detailLevel mini SPHardwareDataType
      - name: Checkout apache/streams.git
        uses: actions/checkout@v2
      - name: Set up Java 1.8
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 1.8
      - name: Restore ~/.m2/repository
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository/
            !~/.m2/repository/org/apache/streams
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: mvn -B -V clean install -ff -ntp
        env:
          MAVEN_OPTS: -Xmx1g -XX:ReservedCodeCacheSize=1g -XX:+UseG1GC -Dorg.slf4j.simpleLogger.defaultLogLevel=INFO
        run: mvn -B -V clean install -ff -ntp
