name: build 

on: [push, pull_request]

jobs:
  ubuntu-java-1-8:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    name: Ubuntu - Java 1.8
    steps:
      - name: checkout apache/streams.git
        uses: actions/checkout@v2
      - name: setup java 1.8
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 1.8
      - name: mvn -B clean install -ff
        env:
          MAVEN_OPTS: -Xmx1g -XX:ReservedCodeCacheSize=1g -XX:+UseG1GC -Dorg.slf4j.simpleLogger.defaultLogLevel=WARN
        run: mvn -B clean install -ff
